### ISSUE TITLE
Problems Flashing

### ISSUE THREAD

**Issue by lockkp1** [Resinchem/ESP-Parking-Assistant#1]
Hi, thanks so much for your write up and code. However I am having issues flashing my D1 mini with the .ino you have. Would you have the .bin file?

I tried to flash my board in NodeMCU Flasher but it doesn't seem to flash the board properly:
Auto-detected Flash size: 4MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.2s
Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.
Compressed 54360 bytes to 13659...
Wrote 54360 bytes (13659 compressed) at 0x00000000 in 1.3 seconds (effective 328.2 kbit/s)...
Hash of data verified.

Leaving...
Staying in bootloader.

Firmware successfully flashed. Unplug/replug or reset device 
to switch back to normal boot mode.

and then I tried to flash in ESPHOME Flasher but that wont flash at all, it gives me errors.

Thank you again

**Comment by Resinchem** [comment]
Are you using the bin file ParkingAsst_v0.33_ESP8266.bin file downloaded from the releases page of this repo: [Releases](https://github.com/Resinchem/ESP-Parking-Assistant/releases/tag/v0.33)?

It appears you are trying to flash the .ino file or maybe the .zip file from downloading the code according to the error, and that won't work in this case.  Just download the .bin from the Releases page and try flashing that.

**Comment by lockkp1** [comment]
Feel a bit dumb, I completely did not see it haha. Thank you so much, flashed properly and now having issues with the TF mini.

Is there anyway to diagnose the sensor? I double checked all my wiring, the lights and everything is working but as I test the distance sensor nothing seems to happen. I set my stanby lights to on to diagnose it and the lights just stay on no matter what I put in front of the sensor. I tried to adjust the values in the parkassist setup site but even still at the lowest values nothing seems to happen. I may have a defective sensor but I just wanted to see if there was anyway to tell?

Thank you so much again

**Comment by Resinchem** [comment]
Unfortunately, since the TFMini-s uses the serial port on the D1 Mini, it can make diagnosing difficult since you can't put out data to a serial monitor at the same time.  But there are a few things to check:
- Make sure you didn't mix up TX/RX - TX on TFMini connects to RX on D1Mini and RX to TX.  Use the supplied cable that comes with the TFMini to verify pin locations/wire colors.
- Assure you have the TFMini-s version.  The TFMini-s (and the TFMini-plus) changed the communication data structure and the library in the code will not work with the original TFMini.
- If you have an MQTT broker, enable MQTT and set telemetry period to minimum 60 seconds.  Place a solid object 2-3 feet from the sensor and see what value it posts to MQTT for parking distance.  If a value of 65533 or 192.0 is consistently reported even if you move the object, it likely means that the TFMini is not communicating because it is either wired wrong or truly is faulty.  

Those are a few ideas to try.  I'm happy to help further, but since this is a separate issue from the original flashing problem, I'm going to go ahead and close this issue.  If you continue to need assistance, you can always open a new issue here, or preferably reach out via the comments section of either the blog or YouTube video and we can take it from there.
