### ISSUE TITLE
Network SSID with special characters won't connect

### ISSUE THREAD

**Issue by hemiawd** [Resinchem/ESP-Parking-Assistant#13]
Ran into issue, network name is NETWORK-2.4G and fails to connect. Using network SSID NETWORK-GUEST and it connects.

I suspect there is a problem handling the "." character in the network name. With tons of devices, changing the network SSID is not possible. Thanks for looking into this

**Comment by Resinchem** [comment]
I suspect this is an issue within the WifiManager library, as that is what handles the onboarding process and the binding to the wifi... I don't actually do anything with the SSID/password in my code.  There do seem to be a couple of similar reported issues within that repository:  [Issue 804](https://github.com/tzapu/WiFiManager/issues/804) and [Issue 906](https://github.com/tzapu/WiFiManager/issues/906).  One is still open and the other has been closed, but I don't see that the problem was specifically fixed.

There have been numerous releases after the one I am currently using, but all are either beta or release-candidates, with no stable/production versions and there are little to no details as to what each new release addresses.  I'm using the latest version before it requires a change from LittleFS to SPIFFS, which is likely to have a major impact on how I'm storing all the other settings. 

I'll leave this issue open and continue to investigate, but there is probably little I can do until the underlying WifiManager library is updated to support special characters in its parameters.

**Comment by hemiawd** [comment]
Thanks. We did further testing and I have not looked at the code yet, but appears to be a length issue. Network name shows correctly but failed to connect to 12 and 13 character SSID with and without special characters. We were able to quickly connect to 6 character SSID and might be more accurate description of the bug.

**Comment by Resinchem** [comment]
Interesting!  I greatly appreciate your assistance in trying to find the cause/solution.  I've spent some time looking at the WifiManager repo, but to be honest, I'm still relatively new to the Arduino/C++ scene.  I looked at all the various posted issues, but It didn't take me long to pretty much get lost looking at their code.  So, you were able to connect to shorter SSIDs that did contain special characters?  If so, then you are right and I will change the issue description to say "longer SSIDs" instead of special characters... or make it both if the shorter SSIDs have problems with the special characters as well.

**Comment by hemiawd** [comment]
I installed as a "gift" so unable to do more testing. The 6 char SSID did not have special characters, we had created a 12 char removing the special was unable to connect leading me to test SSID length as it had worked beautifully in the workshop with a shorter SSID. 

Building a second and will do more extensive testing to answer the remaining questions. I'll also take a look at the code.

**Comment by Resinchem** [comment]
Thanks for the additional testing.  This may in no way be related, but I'm going to add it here for now as something else to consider.  Another user was having connectivity problems... the device would connect the first time, but fail to reconnect on additional attempts (wifimanager.autoconnect returning false).  Here is the info he shared with me regarding what he found:

> I did notice that in the internal wifimanager SSID setup page,  it shows "Authentication Error" after setting up the timeout using the Asus RT-AX86S (although the device is in the Asus device table).  So, I got out my old Asus RT-AC68P router and made a Petrie Dish SSID sub net, and the Wemos D1 connects perfectly and immediately every time

So, at least in his case, it was an issue with a particular router... and obviously something I couldn't duplicate.  Again, might be a completely separate issue, but it does appear that there are some connectivity issues with at least this router... and the same source code connects perfectly with a different router.
.
