### ISSUE TITLE
Upgrade from .42 to .43 lost all settings

### ISSUE THREAD

**Issue by withanhdammit** [Resinchem/ESP-Parking-Assistant#15]
This is mostly just for a heads up.  I upgraded from .42 (original install) to .43 and all settings were lost.  I had to re-set up the wifi access, LED count, distances, etc.

Not sure if there were any other similar reported issues.  I wanted to log this because the notes said I should not have lost my settings.

**Comment by n1kDon** [comment]
Had the same problem.

**Comment by balucanb** [comment]
SAME

**Comment by Resinchem** [comment]
I can't find any reason why this should be happening as the only change in this upgrade was to add default values to the local variables when the values are read from flash, in the event the values do not yet exist in flash.  I've also been unable to replicate the issue on three different systems.  Can anyone experiencing the issue let me know what ESP board they are using?  Again, I don't know why this would have any impact, but I'm just looking for why it appears to happen in some cases, but not in others.

Any additional information you can provide, other than "me too", would be helpful in trying to actually to determine a cause.  In addition to the ESP board you are using, confirming both the old version and the new version involved in the upgrade would be helpful.

However, since it does appear to be happening in some instances, I will add the possibility to the release notes and that you should always record your settings before an upgrade.  I also do not believe this problem will happen or reoccur when upgrading from 0.43 to the latest 0.44 as this upgrade has nothing to do with the values stored in flash nor how they are read. 
 But it might happen when upgrading from anything prior to 0.43 to 0.44.

**Comment by n1kDon** [comment]
Updated from 0.43 to 0.44 and the configuration including wifi credentials was gone. Board: wemos d1 mini clone.

**Comment by balucanb** [comment]
Here is the board I am using.  I had quite a bit of trouble when I went to the newest version. To be fair it could Have been user error, always a consideration. I tried the OTA first then when it came back up it was like it was a new install, another issue was it would no longer connect to the WiFi SSID that I had been using previously. After looking around I saw where others had posted similar issues. Long story short it took me about 5 hours and several attempts of re installing the firmware thru serial and OTA when I gave up and changed the name of the SSID and it worked.
![PXL_20230212_145020806](https://user-images.githubusercontent.com/34525580/218318906-304a25a1-4e8e-4e35-9db8-a3d34f2ee596.jpg)
![PXL_20230212_145049504](https://user-images.githubusercontent.com/34525580/218318923-76af6d1e-0179-49ed-a3d1-91f6a14f9760.jpg)

**Comment by Resinchem** [comment]
I believe I _finally_ found the issue as to why this was occurring in some situations.  A fix is implemented in the v0.46 release.  After upgrading to this version, loss of settings should not occur on future firmware upgrades.  Of course if you experienced it before, it may happen one last time when upgrading to v0.46  as the fix won't be present until after the upgrade.
