### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by marcelk1101** [Resinchem/ESP-Parking-Assistant#23]
Hello, 
thanks for this great idea and development.

I want to know if its possible to get more datapoints on mqtt? I need the state of the leds and the distance. So it would be possible to generate an "live" view.

Would it be possible to update the firmware with wifi?

Thank you very much!

**Comment by Resinchem** [comment]
I'm not sure what you are looking for with MQTT.  I understand that you want updates more often, but distance is already included in the MQTT topics published... as is whether a car is detected or not.  

The same with WiFi.  What are you referring to?  The firmware has WiFi enabled by default and is how you access the web/settings.  It also supports over-the-air firmware updates via WiFi.

As far as changing the frequency of MQTT updates, it will update at least once a minute if you set it at the minimum telemetry time in the settings (60 seconds).  I will also update any time the car "state" changes... e.g. goes from no car detected to car detected (or vice versa).  When the car is just sitting parked (or isn't present), I'm not sure why you would need the distance to be rapidly updated at a more frequent rate.  The same with the LEDs.  I simply saw no reason to flood the MQTT broker with messages when nothing was really changing.  But you may have particular reasons.

I'll mark this as an enhancement request, but to be completely honest, I don't know if or when I may get around to it and would need to have a little better justification and explanation as to what you are really looking for (and why) before I'd consider adding it.

**Comment by marcelk1101** [comment]
Hello,

thank you for your explanation. After I changed the adapter, 3 data points were visible. (Car detected, distance) This is exactly what I need, so it was my mistake.

Now an optimization would be desirable. If you had another data point using MQTT to put the Wemos in standby. So that the lidar sensor is not constantly on. I would connect it to my garage door, i.e. when the door opens the chip is woken up. Is this possible?

Thank you

**Comment by Resinchem** [comment]
While you can certainly make something like that work, it won't be something that I will pursue.  The TFMini Plus lists an average power draw of 550 mW.  That's 0.00055 kW.  Running 24/7 for an entire year would consume about 12 kWh.  And at least here in Indiana, the cost per kWh is $0.15.  That means the cost to run the lidar sensor continuously for an entire year would be about $1.80.  Even adding in the D1 Mini and the standby lights on the LEDs (which can be toggled off in the settings if desired), the cost of the system in standby mode would probably top out at about $3.00-$4.00/year.  It's honestly not worth my time to spend hours rewriting and testing the code to save $4.00 over the course of a year.

Plus if you are going to wake the system with something like the garage door, note that it takes the system anywhere from 15-45 seconds to boot up (depending on how quick the system can join your WiFi, MQTT broker, etc.).  This means the system will not respond to an approaching car until this boot process completes and possibly leaving the driver approaching the parked location with no feedback from the system... unless they want to sit in the driveway waiting for the system to finish booting.

Again, you are free to fork or clone my code and make these changes yourself.  For me, it isn't something I see as worthwhile for my own purposes.

**Comment by marcelk1101** [comment]
Hello,

I would like to thank you very much for the detailed and understandable answer.

However, I still have one question.

We have developed a visualization for the iobroker in our community, similar to Home Assistant. Unfortunately, the data is only updated every 60 seconds, so real-time display is unfortunately not possible. According to your description it is probably the ESP8266. Are there plans to improve this, for example with an ESP32?

I would be very interested.
I would like to thank you in advance and wish you a pleasant Christmas season.

Best Regards, Marcel

**Comment by Resinchem** [comment]
Well, technically the limitation isn't due to the ESP8266 or even the MQTT broker.  But in my case, I have a lot of MQTT devices that probably publish well over a hundred MQTT messages.  In addition, each change to a sensor or value also gets recorded in the Home Assistant log files.  Having a device that publishes messages every 1 or 2 seconds would just unnecessarily tax the broker and bloat the Home Assistant log.  So, for this device, I imposed a 60 second limit due to what I considered "normal" usage.

But both the ESP8266 and MQTT broker could certainly handle an MQTT message at shorter intervals... like once a second.  And if you wanted to change it for this particular app, there are only two minor changes that need to be made.  There is a variable called mqttTelePeriod that is set to 60 seconds by default.  Then where the web page is generated, there is a check that doesn't allow a value of less than 60 to be entered.  You could just change these two values and remove the minimum 60 second limit.

I don't have any plans to develop a version for the ESP32.  Again, the ESP8266 is quite capable of handling the load for the current parking system as it is designed.

**Comment by marcelk1101** [comment]
Perfect, I will test soon. Do you think its possible to Update with OTA, or do I have to write the changed firmware manualy with flashing tool?
